### ISSUE TITLE
Running adaptive_test.TestAdam

### ISSUE THREAD

**Issue by xiaop1987** [lmjohns3/downhill#15]
I'm new to Theano and downhill, when running tests, an exception thrown as flows, any suggestion?
Traceback (most recent call last):
  File "E:/GitHub/downhill/test/adaptive_test.py", line 173, in <module>
    test.test_params()
  File "E:/GitHub/downhill/test/adaptive_test.py", line 163, in test_params
    rms_regularizer=11):
  File "E:\GitHub\downhill\downhill\base.py", line 400, in iterate
    self._compile()
  File "E:\GitHub\downhill\downhill\base.py", line 129, in _compile
    name=label)
  File "C:\Python27\lib\site-packages\theano-0.8.2-py2.7.egg\theano\compile\function.py", line 320, in function
    output_keys=output_keys)
  File "C:\Python27\lib\site-packages\theano-0.8.2-py2.7.egg\theano\compile\pfunc.py", line 442, in pfunc
    no_default_updates=no_default_updates)
  File "C:\Python27\lib\site-packages\theano-0.8.2-py2.7.egg\theano\compile\pfunc.py", line 207, in rebuild_collect_shared
    raise TypeError(err_msg, err_sug)
TypeError: ('An update must have the same type as the original shared variable (shared_var=x_g1_ewma, shared_var.type=TensorType(float32, vector), update_val=Elemwise{add,no_inplace}.0, update_val.type=TensorType(float64, vector)).', 'If the difference is related to the broadcast pattern, you can call the tensor.unbroadcast(var, axis_to_unbroadcast[, ...]) function to remove broadcastable dimensions.')

**Comment by lmjohns3** [comment]
Hm, this is working for me. Maybe we have a mismatch in our theano configs? What is the value of ``floatX`` in your ``.theanorc``?

**Comment by xiaop1987** [comment]
Hi john, that's the problem, thanks a lot.
